# Imports and Setup

In [19]:
import pandas as pd
from sodapy import Socrata

APP_KEY = "t2GPRE1GXlktxvqOIFMelPIvT"

version = "1"

client = Socrata(
    "data.cityofnewyork.us",
    APP_KEY,
    timeout=90
)

RELEASE_NAMES = ["prelim", "exec", "adopt"]

# Expense Budget

https://data.cityofnewyork.us/api/v3/views/mwzb-yiwb/query.json

In [20]:
EXPENSE_DATASET_ID = "mwzb-yiwb"

### Check Fiscal Year

In [21]:
# 1. Fetch the 2 most recent unique fiscal years present in the dataset
year_query = "SELECT fiscal_year GROUP BY fiscal_year ORDER BY fiscal_year DESC LIMIT 2"
current_fy_json = client.get(EXPENSE_DATASET_ID, query=year_query)

In [22]:
# Extract the years into a list, e.g., ['2026', '2025']
planned_fy = [row['fiscal_year'] for row in current_fy_json][0]

planned_fy_name = f"FY{int(planned_fy) % 100}"

print(planned_fy)
print(planned_fy_name)

print()

current_fy = int(planned_fy) - 1
current_fy_name = f"FY{int(current_fy) % 100}"

print(current_fy)
print(current_fy_name)

2027
FY27

2026
FY26

In [23]:
str_sum_current_adopted_amount = f"{current_fy_name}_current_adopted_amount"
str_sum_current_modified_amount = f"{current_fy_name}_current_modified_amount"
str_sum_financial_plan_amount = f"{planned_fy_name}_financial_plan_amount"

str_sum_current_adopted_position = f"{current_fy_name}_current_adopted_position"
str_sum_current_modified_position = f"{current_fy_name}_current_modified_position"
str_sum_financial_plan_position = f"{planned_fy_name}_financial_plan_position"

select_arr = [
    "publication_date",
    "fiscal_year",
    "agency_number",
    "agency_name",
    "unit_appropriation_number",
    "unit_appropriation_name",
    "budget_code_number",
    "budget_code_name",
    "financial_plan_savings_flag",
    f"SUM(adopted_budget_amount) AS {str_sum_current_adopted_amount}",
    f"SUM(current_modified_budget_amount) AS {str_sum_current_modified_amount}",
    f"SUM(financial_plan_amount) AS {str_sum_financial_plan_amount}",
    f"SUM(adopted_budget_position) AS {str_sum_current_adopted_position}",
    f"SUM(current_modified_budget_position) AS {str_sum_current_modified_position}",
    f"SUM(financial_plan_position) AS {str_sum_financial_plan_position}"
]

select_string = ", ".join(select_arr)

print(f"select_string:\n{select_string}\n")

where_string = f"fiscal_year IN ({planned_fy})"

print(f"where_string:\n{where_string}\n")


groupby_arr = [
    "publication_date",
    "fiscal_year",
    "agency_number",
    "agency_name",
    "unit_appropriation_number",
    "unit_appropriation_name",
    "budget_code_number",
    "budget_code_name",
    "financial_plan_savings_flag"
]

groupby_string = ", ".join(groupby_arr)


print(f"groupby_string:\n{groupby_string}\n")



orderby_arr = [
    "agency_number",
    "unit_appropriation_number",
    "budget_code_number",
    "publication_date DESC"
]

orderby_string = ", ".join(orderby_arr)

print(f"orderby_string:\n{orderby_string}\n")



limit = 1000

select_string:
publication_date, fiscal_year, agency_number, agency_name, unit_appropriation_number, unit_appropriation_name, budget_code_number, budget_code_name, financial_plan_savings_flag, SUM(adopted_budget_amount) AS FY26_current_adopted_amount, SUM(current_modified_budget_amount) AS FY26_current_modified_amount, SUM(financial_plan_amount) AS FY27_financial_plan_amount, SUM(adopted_budget_position) AS FY26_current_adopted_position, SUM(current_modified_budget_position) AS FY26_current_modified_position, SUM(financial_plan_position) AS FY27_financial_plan_position

where_string:
fiscal_year IN (2027)

groupby_string:
publication_date, fiscal_year, agency_number, agency_name, unit_appropriation_number, unit_appropriation_name, budget_code_number, budget_code_name, financial_plan_savings_flag

orderby_string:
agency_number, unit_appropriation_number, budget_code_number, publication_date DESC

### Query Data if necessary

In [ ]:
# query_string = f"SELECT {select_string} WHERE {where_string} GROUP BY {groupby_string} ORDER BY {orderby_string} LIMIT {limit}"
# print(query_string)

data = []
offset = 0


# max_item = 0
try:
    df = pd.read_csv(f"./.data_cache/backup_{planned_fy}_v{version}.csv")
except:
    print(f"Querying for fiscal year {planned_fy}_v{version}:\n")
    while True:
        print(f"Fetching rows starting at offset: {offset}")

        temp = client.get(
            dataset_identifier=EXPENSE_DATASET_ID,
            select=select_string,
            where=where_string,
            group=groupby_string,
            order=orderby_string,
            limit=limit,
            offset=offset
        )
        
        if not temp:
            break
        
        # print(temp[0])
        
        data.extend(temp)
        
        offset += limit
            
    print(f"End of query. Successfully fetched {len(data)} total rows.")
    
    len(data)
    
    # Convert to pandas DataFrame
    df = pd.DataFrame.from_records(data)
    # df.drop(columns=["financial_plan_savings_flag"], inplace=True)
    
    df.to_csv(f"./.data_cache/backup_{planned_fy}_v{version}.csv", index=False)

In [25]:
df.columns

Index(['publication_date', 'fiscal_year', 'agency_number', 'agency_name',
       'unit_appropriation_number', 'unit_appropriation_name',
       'budget_code_number', 'budget_code_name', 'financial_plan_savings_flag',
       'FY26_current_adopted_amount', 'FY26_current_modified_amount',
       'FY27_financial_plan_amount', 'FY26_current_adopted_position',
       'FY26_current_modified_position', 'FY27_financial_plan_position'],
      dtype='str')

### Convert to ints

In [26]:


for col in [
    str_sum_current_adopted_amount,
    str_sum_current_modified_amount,
    str_sum_financial_plan_amount,
    str_sum_current_adopted_position,
    str_sum_current_modified_position,
    str_sum_financial_plan_position,
]:
    print(df[col].dtype)
    df[col] = df[col].astype(int)
    print(df[col].dtype)
    print()

int64
int64

int64
int64

int64
int64

int64
int64

int64
int64

int64
int64

In [27]:
df

,publication_date,fiscal_year,agency_number,agency_name,unit_appropriation_number,unit_appropriation_name,budget_code_number,budget_code_name,financial_plan_savings_flag,FY26_current_adopted_amount,FY26_current_modified_amount,FY27_financial_plan_amount,FY26_current_adopted_position,FY26_current_modified_position,FY27_financial_plan_position
0,20260512,2027,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0211,CHIEF OF STAFF,N,14934531,14697531,14937263,149,109,109
1,20260217,2027,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0211,CHIEF OF STAFF,N,14934531,14934531,14937263,149,109,109
2,20260512,2027,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0213,Office of ThriveNYC,N,351980,351980,351980,2,2,2
3,20260217,2027,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0213,Office of ThriveNYC,N,351980,351980,351980,2,2,2
4,20260512,2027,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0214,First Deputy Mayor,N,2306539,2157539,2306539,14,14,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16212,20260217,2027,99C,CITYWIDE SAVINGS INITIATIVES,2,Citywide Savings - OTPS,P010,Fleet Reduction,Y,0,0,-1060000000,0,0,0
16213,20260512,2027,99D,PRIOR YEAR PAYABLES,2,OTHER THAN PERSONAL SERVICES,P002,FINANCIAL PLAN SAVINGS,Y,0,0,-400000000,0,0,0
16214,20260217,2027,99P,ENERGY ADJUSTMENT,2,OTHER THAN PERSONAL SERVICES,P002,FINANCIAL PLAN SAVINGS,Y,0,0,37689973,0,0,0
16215,20260217,2027,99P,ENERGY ADJUSTMENT,2,OTHER THAN PERSONAL SERVICES,P003,Tier IV RECs,Y,0,0,75000000,0,0,0
16216,20260217,2027,99S,LEASE ADJUSTMENT,2,OTHER THAN PERSONAL SERVICES,P002,FINANCIAL PLAN SAVINGS,Y,0,0,53230428,0,0,0

## Track releases

In [28]:
pub_dates = df["publication_date"].sort_values(ascending=True).unique().tolist()

num_pubs_this_year = len(pub_dates)

print(f"{num_pubs_this_year} pub_dates in FY {planned_fy}: {pub_dates}")

2 pub_dates in FY 2027: [20260217, 20260512]

## Set up base DataFrame and map function

In [29]:
base_cols = [
    "agency_number",
    "agency_name",
    "unit_appropriation_number",
    "unit_appropriation_name",
    "budget_code_number",
    "budget_code_name",
    "financial_plan_savings_flag",
]

base_df = df[base_cols].drop_duplicates()
base_df.head()

,agency_number,agency_name,unit_appropriation_number,unit_appropriation_name,budget_code_number,budget_code_name,financial_plan_savings_flag
0,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0211,CHIEF OF STAFF,N
2,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0213,Office of ThriveNYC,N
4,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0214,First Deputy Mayor,N
6,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0217,D/M FOR HEALTH & HUMAN SERVICES,N
8,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0218,SPECIAL EVENTS,N

In [30]:
AGENCY_MAP = df[["agency_number","agency_name"]].drop_duplicates().set_index('agency_number')['agency_name'].to_dict()

UOA_MAP = df.groupby('agency_number')[['unit_appropriation_number', 'unit_appropriation_name']].apply(
    lambda x: dict(zip(x['unit_appropriation_number'], x['unit_appropriation_name']))
).to_dict()

BUDGETCODE_MAP = df.groupby(['agency_number', 'unit_appropriation_number'])[["budget_code_number","budget_code_name"]].apply(lambda x: dict(zip(x['budget_code_number'], x['budget_code_name']))).to_dict()

BUDGETCODE_MAP

{('002', 20): {'0211': 'CHIEF OF STAFF',
  '0213': 'Office of ThriveNYC',
  '0214': 'First Deputy Mayor',
  '0217': 'D/M FOR HEALTH & HUMAN SERVICES',
  '0218': 'SPECIAL EVENTS',
  '0220': 'Intergovernmental Affairs',
  '0222': 'Deputy Mayor for Strategic Policy',
  '0225': 'D/M ECONOMIC DEVEL',
  '0226': 'D/M for Housing & Economic Development',
  '0229': 'Counsel to the Mayor',
  '0230': "Mayor's Judiciary Committee",
  '0235': 'D/M FOR OPERATIONS',
  '0243': 'Citywide Capital Services',
  '0245': 'Comm to Combat Domestic Violence',
  '0248': 'Public Design Commission',
  '0250': 'Office of Immigrant Affairs',
  '0253': 'CAPITAL PROJECT DEVELOPMENT',
  '0264': 'NYC Service Office',
  '0274': 'Citywide Events Coordination & Mgmt.',
  '0277': 'Senior Advisor to the Mayor',
  '0298': 'RECORDS MANAGEMENT GRANT',
  '0332': 'NYC Tourism Grant',
  'P020': 'FINANCIAL PLAN SAVINGS'},
 ('002', 21): {'0211': 'CHIEF OF STAFF',
  '0214': 'First Deputy Mayor',
  '0217': 'D/M FOR HEALTH & HUMAN SERVICES',
  '0218': 'SPECIAL EVENTS',
  '0220': 'Intergovernmental Affairs',
  '0222': 'Deputy Mayor for Strategic Policy',
  '0225': 'D/M ECONOMIC DEVEL',
  '0226': 'D/M for Housing & Economic Development',
  '0227': 'PRESS OFFICE',
  '0228': 'Office of Tenant Protection',
  '0229': 'Counsel to the Mayor',
  '0230': "Mayor's Judiciary Committee",
  '0235': 'D/M FOR OPERATIONS',
  '0240': 'Office of Contract Services',
  '0246': 'Comm to Combat Domestic Violence - City',
  '0250': 'Office of Immigrant Affairs',
  '0264': 'NYC Service Office',
  '0274': 'Citywide Events Coordination & Mgmt.',
  '0277': 'Senior Advisor to the Mayor',
  '0298': 'RECORDS MANAGEMENT GRANT'},
 ('002', 40): {'0401': 'Executive - Budget Director',
  '0402': 'First Deputy DirectorFirst Deputy Direct',
  '0403': 'Personnel Mgt. Admin. & Info. Systems',
  '0408': 'WATER AUTHORITY',
  '0410': 'TRANSITIONAL FINANCE AUTHORITY',
  '0411': 'Education, Intergov Rel',
  '0413': 'Tax Policy, Housing, Econ Dev',
  '0416': 'Tax Policy',
  '0420': 'Infrast. Culturals, CPSD',
  '0421': 'Jus,FD,DOS,DEP,DOT,DDC,DPR,Lib&C,Adm Ag',
  '0423': 'CDBG Administration PS',
  '0431': 'Exp Budget Planning & Control, Comm Bd',
  '0432': 'Labor, Pension, Rev Analysis & Control',
  '0433': 'Cap Plan,Misc Rev,IT,OR',
  '0441': 'Health & Social Services',
  '0449': 'Other Categorical Health',
  '0450': 'Fed- Housing and Homelessness Policy Dev',
  '0451': 'Federal Funds',
  '0462': 'IFA, Value Eng, AM',
  '0478': 'OMB DR IDA STAFF ADMIN',
  '0488': 'FEMA TL PS OMB',
  '0498': 'Energy Efficiency Conservation Block Gra',
  'A003': 'OMB CDBG-DR Staff - ADMIN',
  'CV40': 'FEMA Section 324 Mgmt Costs',
  'E455': 'FEMA Direct Admin Costs',
  'ID93': 'FEMA IDA- PS - OMB',
  'P040': 'FINANCIAL PLAN SAVINGS'},
 ('002', 41): {'0405': 'DIR OMB EXP & CAP',
  '0406': 'OTPS-OMB',
  '0407': 'CDBG Administration OTPS',
  '0408': 'WATER AUTHORITY',
  '0409': 'OTPS-OMB (IFA)',
  '0410': 'TRANSITIONAL FINANCE AUTHORITY',
  '0460': 'FFY23 UASI Grant',
  '0477': 'HURRICANE IDA - CD',
  'A602': 'OMB CDBG-DR General OTPS - ADMIN',
  'P041': 'FINANCIAL PLAN SAVINGS'},
 ('002', 61): {'0601': 'ADMINISTRATION',
  '0602': 'BUR. OF EMPLOYEE BENEFITS',
  '0603': 'STEP III GRIEVANCE I/C DSS',
  '0604': 'ADMINISTRATION',
  '0607': 'PACES',
  '0608': 'MANAGEMENT WELFARE FUND',
  '0610': 'DEFERRED COMPENSATION',
  '0611': 'MUNI LABOR RELATION',
  '0612': 'FLEXIBLE SPENDING PLAN',
  '0620': 'MBF to Reimburse City Funds',
  '0621': 'Pre-Tax Program to Reimburse City Funds',
  '0622': 'NYCHA to Reimburse City Funds',
  '0625': 'NYCHA - EAP',
  '0645': 'UNIT OF APPROPRIATION FUNDING',
  '0650': 'Thrive in Your Workplace',
  '0655': 'Unitof Appropriation Funding OLR/AC',
  'P061': 'FINANCIAL PLAN SAVINGS'},
 ('002', 62): {'0601': 'ADMINISTRATION',
  '0602': 'BUR. OF EMPLOYEE BENEFITS',
  '0604': 'ADMINISTRATION',
  '0607': 'PACES',
  '0613': 'MUNI LABOR RELATION - OTPS',
  '0625': 'NYCHA - EAP',
  '0650': 'Thrive in Your Workplace',
  '0655': 'Unitof Appropriation Funding OLR/AC',
  'P062': 'FINANCIAL PLAN SAVINGS'},
 ('002', 70): {'0710': "Mayor's Office for International Affairs"},
 ('002', 71): {'0714': 'NYC COMM TO THE U N'},
 ('002', 90): {'0910': 'Administration CTL',
  '0911': 'Administration IFA',
  '0912': 'Administration IC',
  '0920': 'Executive CTL',
  '0921': 'Executive IFA',
  '0922': 'Exec HHSA',
  '0926': 'Technology Strategy EDS CTL',
  '0927': 'Technology Strategy EDS IFA',
  '0930': 'General Counsel',
  '0931': 'General Counsel IFA',
  '0936': 'Chief Diversity Office CTL',
  '0942': 'Office of Contract Services - IFA',
  '0945': 'CIP IC',
  '0946': 'CIP CTL',
  '0947': 'OMWBE',
  '0948': 'MOO-DATA',
  '0950': 'Info Technology CTL',
  '0951': 'IT OPS IFA',
  '0952': 'IT HHSA',
  '0960': 'External Affairs CTL',
  '0961': 'External Affairs IFA',
  '0962': 'External Affairs IC',
  '0970': 'Business Optimization CTL',
  '0971': 'Business Optimization IFA',
  '0972': 'LM HHSA',
  '0980': 'Procurement Accelerator CTL',
  '0981': 'Procurement Accelerator IFA',
  '0982': 'PrcAcel HHSA',
  '0991': 'Strategic Initiatives IFA',
  '1006': 'Procurement Ops Infrastructure CW CTL',
  '1043': 'MONS',
  'P090': 'FINANCIAL PLAN SAVINGS'},
 ('002', 91): {'0900': 'Procurement Data Warehouse',
  '0901': 'Technology Strategy',
  '0910': 'Administration CTL',
  '0930': 'General Counsel',
  '0945': 'CIP IC',
  '0946': 'CIP CTL',
  '0947': 'OMWBE',
  '0950': 'Info Technology CTL',
  '0960': 'External Affairs CTL',
  '0970': 'Business Optimization CTL',
  '0979': 'City Council Discretionary',
  '0980': 'Procurement Accelerator CTL',
  '0990': 'Strategic Initiatives CTL',
  '1043': 'MONS',
  'P091': 'FINANCIAL PLAN SAVINGS'},
 ('002', 100): {'1100': 'Office of Mass Engagement'},
 ('002', 101): {'1100': 'Office of Mass Engagement'},
 ('002', 260): {'2610': 'Office for People with Disabilities',
  '2617': 'Office for People with Disabilities- IFA',
  '2620': 'Handicapped Parking Education'},
 ('002', 261): {'2610': 'Office for People with Disabilities',
  '2614': 'OFF PEOPLE W/DISABILITIES',
  '2620': 'Handicapped Parking Education'},
 ('002', 340): {'3420': 'Community Affairs Unit'},
 ('002', 341): {'3424': 'C A U'},
 ('002', 350): {'3510': 'Commission on Women Issues'},
 ('002', 351): {'3514': 'COMM STATUS WOMEN'},
 ('002', 380): {'3810': 'OFF OF OPERATIONS',
  '3812': 'Office of Operations - IFA',
  '3835': "MAYOR'S OFFICE OF ECONOMIC OPPORTUNITY",
  '3840': 'Office of Climate and Resiliency'},
 ('002', 381): {'3814': 'OFF OF OPERATIONS',
  '3840': 'Office of Climate and Resiliency'},
 ('002', 561): {'5654': 'LOFT BOARD OTPS'},
 ('003', 1): {'0101': 'EXECUTIVE MANAGEMENT',
  '0201': 'DEPARTMENTAL OPERATIONS',
  '0204': 'HAVA Funding',
  '0301': 'FINANCE OFFICE',
  '0401': 'DATA PROCESSING OFFICE',
  '0501': 'BROOKLYN OFFICE',
  '0601': 'QUEENS OFFICE',
  '0701': 'BRONX OFFICE',
  '0801': 'NEW YORK OFFICE',
  '0901': 'STATEN ISLAND OFFICE',
  '3000': 'POLL WORKERS- CITYWIDE',
  'P001': 'FINANCIAL PLAN SAVINGS'},
 ('003', 2): {'0201': 'DEPARTMENTAL OPERATIONS',
  '0202': 'ELECTION PAYMENTS',
  '0203': 'DCAS Intracity',
  '0219': 'Absentee Ballot Pre-Paid Postage',
  'P002': 'FINANCIAL PLAN SAVINGS'},
 ('004', 1): {'1000': 'ADMINISTRATION',
  '1001': 'Strategy, Product & Innovation',
  '1002': 'PUBLIC FUNDS AUDIT & ACCOUNTING',
  '1003': 'PUBLIC AFFAIRS',
  '1004': 'TECHNOLOGY',
  '1005': 'CANDIDATE GUIDANCE POLICY',
  '1006': 'Legal',
  '1007': 'Operations & Finance',
  '1008': 'People Operations',
  '1009': 'Diversity, Equity, and Inclusion',
  '2000': 'CAMPAIGN FINANCE FUND',
  '2001': 'UNRECOVERABLE PAYROLL REFUND',
  'P001': 'FINANCIAL PLAN SAVINGS'},
 ('004', 2): {'1001': 'Strategy, Product & Innovation',
  '1002': 'PUBLIC FUNDS AUDIT & ACCOUNTING',
  '1003': 'PUBLIC AFFAIRS',
  '1004': 'TECHNOLOGY',
  '1005': 'CANDIDATE GUIDANCE POLICY',
  '1006': 'Legal',
  '1008': 'People Operations',
  '1009': 'Diversity, Equity, and Inclusion',
  '2000': 'CAMPAIGN FINANCE FUND',
  'P002': 'FINANCIAL PLAN SAVINGS'},
 ('004', 3): {'3000': 'ELECTION FUNDING'},
 ('008', 100): {'1000': 'ADMINISTRATIVE PS', 'P100': 'FINANCIAL PLAN SAVINGS'},
 ('008', 200): {'2000': 'ADMINISTRATIVE-O T P S',
  '2002': 'LOCAL GOVERNMENT RECORDS MGMT',
  'P200': 'FINANCIAL PLAN SAVINGS'},
 ('010', 1): {'0101': 'EXECUTIVE MGMT AND ADMIN',
  'P001': 'FINANCIAL PLAN SAVINGS'},
 ('010', 2): {'0102': 'OTPS ADMINISTRATION',
  '0106': 'PROJECT SNAP-UP',
  '0113': 'NY State Archives Grant',
  'P002': 'FINANCIAL PLAN SAVINGS'},
 ('011', 1): {'0101': 'EXECUTIVE MANAGEMENT',
  '0102': 'ADMINISTRATION',
  '0103': 'TOPOGRAPHIC',
  '0104': 'COMMUNITY RELATIONS',
  '0107': "COMMUNITY & GOV'T LIAISON",
  'P001': 'FINANCIAL PLAN SAVINGS'},
 ('011', 2): {'0102': 'ADMINISTRATION',
  '0103': 'TOPOGRAPHIC',
  'P002': 'FINANCIAL PLAN SAVINGS'},
 ('012', 1): {'0101': 'EXECUTIVE MANAGEMENT',
  '0102': 'ADMINISTRATION',
  '0103': 'TOPOGRAPHICAL',
  '0104': 'COMMUNITY BOARDS',
  '0108': 'ETHNIC RELATIONS',
  '0124': 'Resources for Topographical Unit',
  'P001': 'FINANCIAL PLAN SAVINGS'},
 ('012', 2): {'0102': 'ADMINISTRATION',
  '0103': 'TOPOGRAPHICAL',
  '0124': 'Resources for Topographical Unit'},
 ('013', 1): {'0101': 'EXECUTIVE MANAGEMENT',
  '0102': 'ADMINISTRATION',
  '0103': 'TOPOGRAPHICAL',
  '0104': 'COMMUNITY BOARD LIAISON',
  '0105': 'BOROUGH BOARD',
  '0107': 'ECONOMIC DEVELOPMENT',
  'P001': 'FINANCIAL PLAN SAVINGS'},
 ('013', 2): {'0102': 'ADMINISTRATION',
  '0129': 'Flushing Meadows Corona Park',
  '0130': 'VIOLENCE AGAINST WOMEN (VAWA) GRANT',
  'P002': 'FINANCIAL PLAN SAVINGS'},
 ('014', 1): {'0101': 'EXECUTIVE MANAGEMENT',
  '0102': 'ADMINISTRATION',
  '0103': 'TOPOGRAPHICAL',
  '0104': 'SUPPORT SERVICES',
  'P001': 'FINANCIAL PLAN SAVINGS'},
 ('014', 2): {'0102': 'ADMINISTRATION', 'P002': 'FINANCIAL PLAN SAVINGS'},
 ('015', 1): {'0101': 'EXECUTIVE OFFICE', '1000': 'CENTRAL'},
 ('015', 2): {'0501': 'BUREAU OF ADMINISTRATIVE SERVI',
  '0601': 'BUREAU OF FISCAL & BUDGET STUD',
  '0702': 'INFORMATION SYSTEMS',
  '0801': 'BUREAU OF AUDIT',
  '0802': 'BUREAU OF AUDIT - IFA',
  '0804': 'COMMUNITY RELATIONS/CITIZENS A',
  '0805': 'OFFICE OF POLICY MAN',
  '1001': 'BUREAU OF ACCOUNTANCY',
  '1002': 'Bureau of Accountancy - IFA',
  '1100': 'BUREAU OF ENGINEERING-IFA',
  '2000': 'CENTRAL'},
 ('015', 3): {'1101': 'GENERAL COUNSEL',
  '1105': 'CONTRACT ADMINISTRATION',
  '1106': 'Contract Adminitration - IFA',
  '1200': 'BUREAU OF LAW AND ADJUSTMENT',
  '1202': 'LABOR LAW - IFA',
  '1203': 'Labor Law CTL',
  '1205': 'LAW AND ADJUSTMENT-IFA',
  '3000': 'Central'},
 ('015', 4): {'1400': 'BUREAU OF ASSET MANAGEMENT',
  '1401': 'DEPUTY COMPTROLLER F',
  '1405': 'Asset Management - Grant'},
 ('015', 5): {'0401': 'FIRST DEPUTY COMPTROLLER',
  '0501': 'BUREAU OF ADMINISTRATIVE SERVI',
  '0502': 'OFFICE OF FISCAL SERVICES',
  '0601': 'BUREAU OF FISCAL & BUDGET STUD',
  '0702': 'INFORMATION SYSTEMS',
  '0801': 'BUREAU OF AUDIT',
  '1001': 'BUREAU OF ACCOUNTANCY',
  '5000': 'ADM Central Mgmt 5000'},
 ('015', 6): {'0102': 'Policy Management',
  '0103': 'Public Affairs',
  '0111': 'EXECUTIVE OFFICE',
  '6000': 'ADM Central Mgmt 6000'},
 ('015', 7): {'1101': 'GENERAL COUNSEL',
  '1103': 'ENGINEERING',
  '1105': 'CONTRACT ADMINISTRATION',
  '1200': 'BUREAU OF LAW AND ADJUSTMENT',
  '1202': 'LABOR LAW - IFA',
  '1303': 'Labor Law CTL',
  '7000': 'ADM Central Mgmt 7000'},
 ('015', 8): {'1400': 'BUREAU OF ASSET MANAGEMENT',
  '1401': 'DEPUTY COMPTROLLER F',
  '1402': 'ASSET MANAGEMENT-INVESTMENTS',
  '1405': 'Asset Management - Grant',
  '8000': 'ADM Central Mgmt 8000'},
 ('017', 1): {'1000': 'Emergency Management PS',
  '1042': 'CB for Capped Grants',
  '1105': 'Special City Project - PS',
  '1124': 'FY24 EMPG',
  '2647': '2024 USAR COOPERATIVE AGREEMENT',
  '2657': 'USAR 2025 COOPERATIVE AGREEMENT',
  '2980': '23 UASI PS',
  '3050': 'Notify NYC Langauge Legislation',
  '4023': 'HMGP 4567-DR',
  '4107': 'CD- Community Outreach Specialist',
  '4108': 'CD- Housing Recovery Program Manager',
  '4109': 'CD- Recovery Program Manager',
  '4110': 'CD - Mitigation Grant Program Manager',
  '4111': 'CD - Data Governance',
  '4112': 'CD - Flood Program Manger',
  'HG24': '24 UASI GRANT'},
 ('017', 2): {'0200': 'Executive',
  '0201': 'Administration & Travel',
  '0202': 'Readiness - Training and Exercises',
  '0203': 'Security',
  '0204': 'Information Technology',
  '0205': 'Operations',
  '0206': 'Legal',
  '0207': 'External Affairs',
  '0208': 'Strategy & Program Development',
  '0210': 'Community Preparedness',
  '0212': 'Intracity Services',
  '0213': 'Human Resources',
  '0214': 'Logistics General',
  '1106': 'Special City Project - OTPS',
  '1124': 'FY24 EMPG',
  '1201': 'FY23 Emergency Operrations Center',
  '1202': 'FY24 DSANY',
  '2000': 'Support Services - COO',
  '2097': 'Solomon - Fund for the City of NY',
  '2114': 'Emergency Preparedness Event Member Item',
  '2126': 'FY23 Cooperating Technical PartnersGrnt',
  '2127': 'FY24 Cooperating Technical PartnersGrnt',
  '2500': "MAYOR'S FUND TO ADVANCE NY",
  '2634': 'USAR Hurricane Ida',
  '2643': 'USAR 2023 COOP AGREEMENT',
  '2647': '2024 USAR COOPERATIVE AGREEMENT',
  '2649': 'US&R HURRICANE BERYL DEPLOYMENT',
  '2656': 'US&R TEXAS FLOOD DEPLOYMENT',
  '2657': 'USAR 2025 COOPERATIVE AGREEMENT',
  '2969': '22 UASI TECH',
  '2970': '22 UASI HUM. LOGS',
  '2974': '22 UASI NOTIFY NYC - Response',
  '2981': '23 UASI RNY - Community Preparedness',
  '2982': '23 UASI RNY - External Affairs',
  '2983': '23 UASI CERT',
  '2984': '23 UASI COOP',
  '2985': '23 UASI GIS',
  '2987': '23 UASI P&R - Interagency Coordination',
  '2988': '23 UASI P&R - Risk Reduction & Recovery',
  '2989': '23 UASI Tech',
  '2990': '23 UASI Humanitarian Logs',
  '2991': '23 UASI Supply Chain Logs',
  '2992': '23 UASI Travel',
  '2993': '23 UASI NotifyNYC - Strategic Ops',
  '2994': '23 UASI NotifyNYC - Response',
  '2995': '23 UASI T&E',
  '2996': '23 UASI Support Services',
  '2997': '23 UASI M&A',
  '3000': 'Emergency Budget Code',
  '3016': 'Private Grant - RNY',
  '3030': 'Flood Protection - Trap Bags',
  '3050': 'Notify NYC Langauge Legislation',
  '4023': 'HMGP 4567-DR',
  '4102': 'CD - Evacuation Modeling',
  '4103': 'CD - IMPACT ASSESSMENTS',
  '4104': 'CD - NOTIFYNYC LANGUAGE OUTREACH',
  '4105': 'CD- HOUSING RECOVERY PROGRAM ANALYSIS',
  '4106': 'CD- WEATHER MONITORING',
  '4111': 'CD - Data Governance',
  '4113': 'CD - Strengthening Communities',
  'HG24': '24 UASI GRANT',
  'J002': 'Weather Related Cost',
  'M002': 'Asylum Support',
  'P002': 'FINANCIAL PLAN SAVINGS'},
 ('021', 1): {'1001': 'AGENCYWIDE OPERATIONS',
  '2002': 'Other Than Real Property Taxes',
  'P001': 'FINANCIAL PLAN SAVINGS'},
 ('021', 2): {'1001': 'AGENCYWIDE OPERATIONS',
  'P002': 'FINANCIAL PLAN SAVINGS'},
 ('025', 1): {'0101': 'EXECUTIVE',
  '0104': 'MOPD - PEOPLE WITH DISABILITIES',
  '0109': 'EXECUTIVE RAISE THE AGE',
  '0201': 'ADMINISTRATIVE SERVICES DIV.',
  '0209': 'ADMINISTRATION RAISE THE AGE',
  '0301': 'APPEALS DIVISION',
  '0302': 'APPEALS-IFA',
  '0309': 'APPEALS RAISE THE AGE',
  '0601': 'CONTRACTS',
  '0602': 'CONTRACTS & REAL ESTATE-IFA',
  '0701': 'OPERATIONS SUPPORT',
  '0709': 'OPERATION RAISE THE AGE',
  '0901': 'FAMILY COURT-USDL',
  '0902': 'FAMILY COURT-USDL',
  '0907': 'Raise the Age - State',
  '0909': 'FAMILY COURT RAISE THE AGE',
  '1001': 'GENERAL LITIGATION DIVISION',
  '1201': 'LEGAL COUNSEL',
  '1301': 'ADMINISTRATIVE LAW DIVISION',
  '1303': 'INTRA-CITY LAW/HEALTH LEGAL SERVICES',
  '1304': 'OFFICE OF SPECIAL ENFORCEMENT',
  '1305': 'ADMIN LAW - CRIMINAL JUSTICE REFORM',
  '1501': 'AFFIRMATIVE LITIGATION',
  '1506': 'OFFICE OF SPECIAL ENFORCEMENT (AF)',
  '1701': "WORKER'S COMPENSATION DIV",
  '1702': 'IC HHC SERVICES',
  '2001': 'TORT DIVISION',
  '2003': 'TORT WORLD TRADE CENTER',
  '2005': 'TORT - SLU',
  '2006': 'TORT - SLED',
  '2101': 'COMMERCIAL LITIGATION DIV',
  '2102': 'COMMERCIAL LITIGATION-IFA',
  '2201': 'ECONOMIC DEVELOPMENT DIV',
  '2202': 'ECONOMIC DEVELOPMENT-IFA',
  '2203': 'NYC & CO LEGAL REIMBURSEMENT',
  '2204': 'OC EDC LEGAL SERVICES',
  '2301': 'MUNICIPAL FINANCE',
  '2401': 'ENVIRONENTAL LAW',
  '2402': 'ENVIRONMENTAL LAW-IFA',
  '2501': 'SPECIAL FEDERAL LITIGATION',
  '2801': 'LABOR & EMPLOYMENT LAW',
  '2802': 'IC HHC SERVICES - LE',
  '2901': 'TAX & BANKRUPTCY LITIGATION',
  '3001': 'INFORMATION TECHNOLOGY DIVISION',
  '3009': 'IT RAISE THE AGE',
  '3200': 'LITIGATION SUPPORT UNIT',
  '3201': 'LITIGATION SUPPORT DIVISION',
  '3205': 'LIT SUPPORT - CRIMINAL JUSTICE REFORM',
  '3401': 'E-DISCOVERY GROUP',
  '3402': 'RISK MANAGEMENT',
  '3403': 'ETHICS AND COMPLIANCE',
  'P001': 'FINANCIAL PLAN SAVINGS'},
 ('025', 2): {'0107': 'NYCHA Matter',
  '0201': 'ADMINISTRATIVE SERVICES DIV.',
  '0207': 'ADMINISTRATION - FISCAL MISC. PAYMENTS',
  '0208': "ADMINISTRATION-CASHIER'S MISC. PAYMENTS",
  '0211': 'DCP RENT 60 BAY STREET 4TH. FLOOR',
  '0902': 'FAMILY COURT-USDL',
  '0907': 'Raise the Age - State',
  '0909': 'FAMILY COURT RAISE THE AGE',
  '1001': 'GENERAL LITIGATION DIVISION',
  '1003': 'DOC AGREEMENT',
  '1202': 'HOGAN LOVELLS - DOE',
  '1303': 'INTRA-CITY LAW/HEALTH LEGAL SERVICES',
  '1306': 'American Council of The Blind Matter',
  '1501': 'AFFIRMATIVE LITIGATION',
  '1502': 'DEP LEGAL SERVICES/ENERGY',
  '1508': 'Cannabis Enforcement - AF',
  '1509': 'COLLECTIONS AGENCIES',
  '1601': 'MANAGEMENT INFO SVCS',
  '1701': "WORKER'S COMPENSATION DIV",
  '1702': 'IC HHC SERVICES',
  '2001': 'TORT DIVISION',
  '2004': 'DOT LEGAL SERVICES',
  '2015': 'Misc. Budget transfered funds',
  '2203': 'NYC & CO LEGAL REIMBURSEMENT',
  '2205': 'ECONOMIC DEVELOPMENT DIV - DCAS SVCS',
  '2403': 'DEP Legal and Consultant Services',
  '2406': 'DEP SOMACH INTRACITY',
  '2504': 'Floyd Matter',
  '2505': 'Nunez Matter',
  '2506': 'Nunez RM',
  '2802': 'IC HHC SERVICES - LE',
  '2803': 'Gulino Matter',
  '2804': 'Vulcan Matter',
  '3102': 'CHARTER REVISION COMMISSION 2024',
  '3103': 'FY25 CHARTER REVISION',
  '3206': 'CityAdmin',
  'P002': 'FINANCIAL PLAN SAVINGS',
  'Z231': 'PlaNYC - Energy'},
 ('030', 1): {'1000': 'Executive and Admin  (Tax Levy)',
  '1001': 'Admin (CDBG)',
  '2000': 'Planning Coordination (Tax Levy)',
  '2001': 'PLANNING COORDINATION DIVISION',
  '2100': 'Capital/Regional Planning (Tax Levy)',
  '2101': 'Capital/Regional (CDBG)',
  '2200': 'Zoning/Urban Design',
  '2201': 'Zoning/Urban Design (CDBG)',
  '2300': 'HEIP/ Population (Tax Levy)',
  '2301': 'HEIP/ Population (CDBG)',
  '2400': 'Strategic Planning (Tax Levy)',
  '2401': 'Strategic Planning (CDBG)',
  '2500': 'TRANSPORTATION PLANNING',
  '2503': 'TRANSPORTATION (FED)',
  '2600': 'Waterfront (Tax)',
  '2601': 'Waterfront (CDBG)',
  '2602': 'Waterfront (State)',
  '2612': 'Waterfront Action Agenda (EPF LWRP)',
  '3000': 'Borough Offices - Tax Levy',
  '3001': 'BOROUGH OFFICES (CDBG)',
  '4000': 'COMPUTER INFORMATION SVCS (General)',
  '4001': 'COMPUTER INFORMATION SVCS (General)',
  '5100': 'LAND USE REVIEW',
  '5200': 'TECHNICAL REVIEW DIVISION',
  '5300': 'EARD (Tax Levy)',
  '6101': 'Consolidated Plan Transition',
  '7001': 'IDA NEIGHBORHOOD STUDY: CONEY ISLAND',
  '7011': 'IDA NEIGHBORHOOD STUDY: WILLIAMSBURG',
  '7031': 'IDA STORMWATER FLOODING STUDY',
  '7061': 'PRO-CEQR App Development',
  'P001': 'FINANCIAL PLAN SAVINGS'},
 ('030', 2): {'0170': 'Agency Lease',
  '0200': 'ADMINISTRATION',
  '0300': 'AGENCYWIDE OTPS - GENERAL',
  '0500': 'EIS (Tax Levy)',
  '0510': 'DEP-DCP ISR INTRA-CITY',
  '2001': 'PLANNING COORDINATION DIVISION',
  '2503': 'TRANSPORTATION (FED)',
  '3001': 'BOROUGH OFFICES (CDBG)',
  '4000': 'COMPUTER INFORMATION SVCS (General)',
  '4120': 'COMPUTER INFORMATION SVCS (Restricted)',
  '5000': 'PAPERLESS FILING',
  '6101': 'Consolidated Plan Transition',
  '7001': 'IDA NEIGHBORHOOD STUDY: CONEY ISLAND',
  '7011': 'IDA NEIGHBORHOOD STUDY: WILLIAMSBURG',
  '7021': 'IDA CDBG-DR: JEWEL STREET',
  '7051': 'PRO-Jamaica Neighborhood Rezoning',

## Loop through each release

In [31]:
print(pub_dates)

print(planned_fy)

for i, pub_date in enumerate(pub_dates):
    release_name = RELEASE_NAMES[i]
    
    ith_release_df = df[df['publication_date'] == pub_date]
    
    print(i, release_name)

[20260217, 20260512]
2027
0 prelim
1 exec

## Budget Codes

In [32]:
target_cols = [
    "agency_number",
    "unit_appropriation_number",
    "budget_code_number",
    "financial_plan_savings_flag",
    f"{str_sum_current_adopted_amount}",
    f"{str_sum_current_modified_amount}",
    f"{str_sum_financial_plan_amount}",
    f"{str_sum_current_adopted_position}",
    f"{str_sum_current_modified_position}",
    f"{str_sum_financial_plan_position}",
]


collapsed_df = base_df.copy()

for i, pub_date in enumerate(pub_dates):
    ith_release_df = df[df["publication_date"] == pub_date][target_cols].copy()
    
    print(i)
    
    if i <= 2:
        ith_release_df = ith_release_df.rename(
            columns={
                f"{str_sum_financial_plan_amount}":f"{str_sum_financial_plan_amount}_{RELEASE_NAMES[i]}",
                f"{str_sum_financial_plan_position}":f"{str_sum_financial_plan_position}_{RELEASE_NAMES[i]}"
                }
        )
    else:
        raise Exception(f"Bad indexing, i:{i} >= num_pubs_this_year or i:{i} < 0")
    
    if i < num_pubs_this_year - 1:
        ith_release_df = ith_release_df.drop(columns=[
            f"{str_sum_current_adopted_amount}",
            f"{str_sum_current_modified_amount}",
            f"{str_sum_current_adopted_position}",
            f"{str_sum_current_modified_position}"
            ])
    
    print(f"[{i}/{num_pubs_this_year}] pub_date -- {pub_date} ({RELEASE_NAMES[i]}):")
    print(ith_release_df.columns)
    print()
    
    collapsed_df = collapsed_df.merge(right=ith_release_df,on=["agency_number","unit_appropriation_number","budget_code_number", "financial_plan_savings_flag"], how='left')

collapsed_df = collapsed_df.fillna(0)

0
[0/2] pub_date -- 20260217 (prelim):
Index(['agency_number', 'unit_appropriation_number', 'budget_code_number',
       'financial_plan_savings_flag', 'FY27_financial_plan_amount_prelim',
       'FY27_financial_plan_position_prelim'],
      dtype='str')

1
[1/2] pub_date -- 20260512 (exec):
Index(['agency_number', 'unit_appropriation_number', 'budget_code_number',
       'financial_plan_savings_flag', 'FY26_current_adopted_amount',
       'FY26_current_modified_amount', 'FY27_financial_plan_amount_exec',
       'FY26_current_adopted_position', 'FY26_current_modified_position',
       'FY27_financial_plan_position_exec'],
      dtype='str')

In [33]:
print(collapsed_df.columns)

collapsed_df.head()

Index(['agency_number', 'agency_name', 'unit_appropriation_number',
       'unit_appropriation_name', 'budget_code_number', 'budget_code_name',
       'financial_plan_savings_flag', 'FY27_financial_plan_amount_prelim',
       'FY27_financial_plan_position_prelim', 'FY26_current_adopted_amount',
       'FY26_current_modified_amount', 'FY27_financial_plan_amount_exec',
       'FY26_current_adopted_position', 'FY26_current_modified_position',
       'FY27_financial_plan_position_exec'],
      dtype='str')

,agency_number,agency_name,unit_appropriation_number,unit_appropriation_name,budget_code_number,budget_code_name,financial_plan_savings_flag,FY27_financial_plan_amount_prelim,FY27_financial_plan_position_prelim,FY26_current_adopted_amount,FY26_current_modified_amount,FY27_financial_plan_amount_exec,FY26_current_adopted_position,FY26_current_modified_position,FY27_financial_plan_position_exec
0,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0211,CHIEF OF STAFF,N,14937263.0,109.0,14934531.0,14697531.0,14937263.0,149.0,109.0,109.0
1,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0213,Office of ThriveNYC,N,351980.0,2.0,351980.0,351980.0,351980.0,2.0,2.0,2.0
2,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0214,First Deputy Mayor,N,2306539.0,14.0,2306539.0,2157539.0,2306539.0,14.0,14.0,14.0
3,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0217,D/M FOR HEALTH & HUMAN SERVICES,N,1348827.0,7.0,1348827.0,1348827.0,1348827.0,7.0,7.0,7.0
4,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0218,SPECIAL EVENTS,N,1989369.0,20.0,1989369.0,1989369.0,1989369.0,20.0,20.0,20.0

In [34]:
# for j in range(0,i):
#     print(f"i={i}, j={j}")
#     print(f"{RELEASE_NAMES[i]} - {RELEASE_NAMES[j]}")
    
#     i_amount_name = f"{str_sum_financial_plan_amount}_{RELEASE_NAMES[i]}"
#     j_amount_name = f"{str_sum_financial_plan_amount}_{RELEASE_NAMES[j]}"
    
#     i_position_name = f"{str_sum_financial_plan_position}_{RELEASE_NAMES[i]}"
#     j_position_name = f"{str_sum_financial_plan_position}_{RELEASE_NAMES[j]}"
    
#     print()
#     print(f"i_amount_name: {i_amount_name}")
#     print(f"j_amount_name: {j_amount_name}")
#     print()
#     print(f"i_position_name: {i_position_name}")
#     print(f"j_position_name: {j_position_name}")
#     print()
        
        
#     amount_change_name = f"{str_sum_financial_plan_amount}_change_{RELEASE_NAMES[i]}-{RELEASE_NAMES[j]}"
#     amount_change_percent_name = f"{str_sum_financial_plan_amount}_%change_{RELEASE_NAMES[i]}-{RELEASE_NAMES[j]}"
    
#     print(amount_change_name)
#     print(amount_change_percent_name)
        
#     collapsed_df[amount_change_name] = collapsed_df[i_amount_name] - collapsed_df[j_amount_name]
#     collapsed_df[amount_change_percent_name] = (collapsed_df[i_amount_name] - collapsed_df[j_amount_name])/collapsed_df[i_amount_name]
    
    
#     print()
    
#     position_change_name = f"{str_sum_financial_plan_position}_change_{RELEASE_NAMES[i]}-{RELEASE_NAMES[j]}"
#     position_change_percent_name = f"{str_sum_financial_plan_position}_%change_{RELEASE_NAMES[i]}-{RELEASE_NAMES[j]}"
    
#     print(position_change_name)
#     print(position_change_percent_name)
    
#     collapsed_df[position_change_name] = collapsed_df[i_position_name] - collapsed_df[j_position_name]
#     collapsed_df[position_change_percent_name] = (collapsed_df[i_position_name] - collapsed_df[j_position_name])/collapsed_df[i_position_name]
    
#     print("="*50)

In [35]:
collapsed_df

,agency_number,agency_name,unit_appropriation_number,unit_appropriation_name,budget_code_number,budget_code_name,financial_plan_savings_flag,FY27_financial_plan_amount_prelim,FY27_financial_plan_position_prelim,FY26_current_adopted_amount,FY26_current_modified_amount,FY27_financial_plan_amount_exec,FY26_current_adopted_position,FY26_current_modified_position,FY27_financial_plan_position_exec
0,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0211,CHIEF OF STAFF,N,1.493726e+07,109.0,14934531.0,14697531.0,14937263.0,149.0,109.0,109.0
1,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0213,Office of ThriveNYC,N,3.519800e+05,2.0,351980.0,351980.0,351980.0,2.0,2.0,2.0
2,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0214,First Deputy Mayor,N,2.306539e+06,14.0,2306539.0,2157539.0,2306539.0,14.0,14.0,14.0
3,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0217,D/M FOR HEALTH & HUMAN SERVICES,N,1.348827e+06,7.0,1348827.0,1348827.0,1348827.0,7.0,7.0,7.0
4,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0218,SPECIAL EVENTS,N,1.989369e+06,20.0,1989369.0,1989369.0,1989369.0,20.0,20.0,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8255,99C,CITYWIDE SAVINGS INITIATIVES,2,Citywide Savings - OTPS,P010,Fleet Reduction,Y,-1.060000e+09,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8256,99D,PRIOR YEAR PAYABLES,2,OTHER THAN PERSONAL SERVICES,P002,FINANCIAL PLAN SAVINGS,Y,0.000000e+00,0.0,0.0,0.0,-400000000.0,0.0,0.0,0.0
8257,99P,ENERGY ADJUSTMENT,2,OTHER THAN PERSONAL SERVICES,P002,FINANCIAL PLAN SAVINGS,Y,3.768997e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8258,99P,ENERGY ADJUSTMENT,2,OTHER THAN PERSONAL SERVICES,P003,Tier IV RECs,Y,7.500000e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8259,99S,LEASE ADJUSTMENT,2,OTHER THAN PERSONAL SERVICES,P002,FINANCIAL PLAN SAVINGS,Y,5.323043e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [36]:
# # "total_adopted_budget_amount",
# # "total_current_modified_budget_amount",
# # "total_adopted_budget_position",
# # "total_current_modified_budget_position"

# str_sum_current_adopted_amount
# str_sum_current_modified_amount

# str_sum_current_adopted_position
# str_sum_current_modified_position


# amount_change_prev_adopt_name = f"{str_sum_financial_plan_amount}_change_{RELEASE_NAMES[i]}-{current_fy_name}_adopt"
# amount_change_percent_prev_adopt_name = f"{str_sum_financial_plan_amount}_%change_{RELEASE_NAMES[i]}-{current_fy_name}_adopt"

# collapsed_df[amount_change_prev_adopt_name]= collapsed_df[i_amount_name] - collapsed_df[str_sum_current_adopted_amount]
# collapsed_df[amount_change_percent_prev_adopt_name]= (collapsed_df[i_amount_name] - collapsed_df[str_sum_current_adopted_amount])/collapsed_df[i_amount_name]


# amount_change_prev_modified_name = f"{str_sum_financial_plan_amount}_change_{RELEASE_NAMES[i]}-{current_fy_name}_modified"
# amount_change_percent_prev_modified_name = f"{str_sum_financial_plan_amount}_%change_{RELEASE_NAMES[i]}-{current_fy_name}_modified"

# collapsed_df[amount_change_prev_modified_name] = collapsed_df[i_amount_name] - collapsed_df[str_sum_current_modified_amount]
# collapsed_df[amount_change_percent_prev_modified_name] = (collapsed_df[i_amount_name] - collapsed_df[str_sum_current_modified_amount])/collapsed_df[i_amount_name]


# position_change_prev_adopt_name = f"{str_sum_financial_plan_position}_change_{RELEASE_NAMES[i]}-{current_fy_name}_adopt"
# position_change_prev_modified_name = f"{str_sum_financial_plan_position}_change_{RELEASE_NAMES[i]}-{current_fy_name}_modified"

# collapsed_df[position_change_prev_adopt_name] = collapsed_df[i_position_name] - collapsed_df[str_sum_current_adopted_position]
# collapsed_df[position_change_prev_modified_name] = collapsed_df[i_position_name] - collapsed_df[str_sum_current_modified_position]

# # collapsed_df[f"total_financial_plan_position_%change_{RELEASE_NAMES[i]}-adopt"] = (collapsed_df[i_position_name] - collapsed_df["total_adopted_budget_position"])/collapsed_df[i_position_name]
# # collapsed_df[f"total_financial_plan_position_%change_{RELEASE_NAMES[i]}-modified"] = (collapsed_df[i_position_name] - collapsed_df["total_current_modified_budget_position"])/collapsed_df[i_position_name]

In [37]:
collapsed_df

,agency_number,agency_name,unit_appropriation_number,unit_appropriation_name,budget_code_number,budget_code_name,financial_plan_savings_flag,FY27_financial_plan_amount_prelim,FY27_financial_plan_position_prelim,FY26_current_adopted_amount,FY26_current_modified_amount,FY27_financial_plan_amount_exec,FY26_current_adopted_position,FY26_current_modified_position,FY27_financial_plan_position_exec
0,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0211,CHIEF OF STAFF,N,1.493726e+07,109.0,14934531.0,14697531.0,14937263.0,149.0,109.0,109.0
1,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0213,Office of ThriveNYC,N,3.519800e+05,2.0,351980.0,351980.0,351980.0,2.0,2.0,2.0
2,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0214,First Deputy Mayor,N,2.306539e+06,14.0,2306539.0,2157539.0,2306539.0,14.0,14.0,14.0
3,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0217,D/M FOR HEALTH & HUMAN SERVICES,N,1.348827e+06,7.0,1348827.0,1348827.0,1348827.0,7.0,7.0,7.0
4,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,0218,SPECIAL EVENTS,N,1.989369e+06,20.0,1989369.0,1989369.0,1989369.0,20.0,20.0,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8255,99C,CITYWIDE SAVINGS INITIATIVES,2,Citywide Savings - OTPS,P010,Fleet Reduction,Y,-1.060000e+09,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8256,99D,PRIOR YEAR PAYABLES,2,OTHER THAN PERSONAL SERVICES,P002,FINANCIAL PLAN SAVINGS,Y,0.000000e+00,0.0,0.0,0.0,-400000000.0,0.0,0.0,0.0
8257,99P,ENERGY ADJUSTMENT,2,OTHER THAN PERSONAL SERVICES,P002,FINANCIAL PLAN SAVINGS,Y,3.768997e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8258,99P,ENERGY ADJUSTMENT,2,OTHER THAN PERSONAL SERVICES,P003,Tier IV RECs,Y,7.500000e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8259,99S,LEASE ADJUSTMENT,2,OTHER THAN PERSONAL SERVICES,P002,FINANCIAL PLAN SAVINGS,Y,5.323043e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [38]:
for c in collapsed_df.columns:
    print(c)

agency_number
agency_name
unit_appropriation_number
unit_appropriation_name
budget_code_number
budget_code_name
financial_plan_savings_flag
FY27_financial_plan_amount_prelim
FY27_financial_plan_position_prelim
FY26_current_adopted_amount
FY26_current_modified_amount
FY27_financial_plan_amount_exec
FY26_current_adopted_position
FY26_current_modified_position
FY27_financial_plan_position_exec

In [39]:
collapsed_df.to_excel(f"current_api_{planned_fy}.xlsx",sheet_name="Budget Codes",index=False)

## Units of Appropriation

In [40]:
collapsed_df.columns

Index(['agency_number', 'agency_name', 'unit_appropriation_number',
       'unit_appropriation_name', 'budget_code_number', 'budget_code_name',
       'financial_plan_savings_flag', 'FY27_financial_plan_amount_prelim',
       'FY27_financial_plan_position_prelim', 'FY26_current_adopted_amount',
       'FY26_current_modified_amount', 'FY27_financial_plan_amount_exec',
       'FY26_current_adopted_position', 'FY26_current_modified_position',
       'FY27_financial_plan_position_exec'],
      dtype='str')

In [41]:
print(len(['agency_number', 'agency_name', 'unit_appropriation_number',
       'unit_appropriation_name', 'financial_plan_savings_flag']))

5

In [42]:
UoA_collapsed_df = collapsed_df.groupby(['agency_number', 'agency_name', 'unit_appropriation_number', 'unit_appropriation_name', 'financial_plan_savings_flag']).sum().reset_index()

# print(UoA_collapsed_df.columns[7:])

target_cols = UoA_collapsed_df.columns[7:]

UoA_collapsed_df = UoA_collapsed_df[['agency_number', 'agency_name', 'unit_appropriation_number', 'unit_appropriation_name', 'financial_plan_savings_flag',*target_cols]]

UoA_collapsed_df

,agency_number,agency_name,unit_appropriation_number,unit_appropriation_name,financial_plan_savings_flag,FY27_financial_plan_amount_prelim,FY27_financial_plan_position_prelim,FY26_current_adopted_amount,FY26_current_modified_amount,FY27_financial_plan_amount_exec,FY26_current_adopted_position,FY26_current_modified_position,FY27_financial_plan_position_exec
0,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,N,4.046508e+07,278.0,40515979.0,40316729.0,40465085.0,319.0,279.0,278.0
1,002,MAYORALTY,20,OFFICE OF THE MAYOR-PS,Y,0.000000e+00,40.0,0.0,0.0,6286117.0,0.0,40.0,44.0
2,002,MAYORALTY,21,OFFICE OF THE MAYOR-OTPS,N,4.489982e+06,0.0,4237982.0,4459520.0,5031799.0,0.0,0.0,0.0
3,002,MAYORALTY,40,OFFICE OF MGMT AND BUDGET-PS,N,5.588977e+07,467.0,55263233.0,54555072.0,56564894.0,455.0,452.0,474.0
4,002,MAYORALTY,40,OFFICE OF MGMT AND BUDGET-PS,Y,1.774270e+05,0.0,177416.0,177416.0,-664573.0,0.0,0.0,-7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,945,PUBLIC ADMINISTRATOR-RICHMOND COUNTY,2,OTHER THAN PERSONAL SERVICES,Y,-2.637000e+03,0.0,22363.0,97.0,-2637.0,0.0,0.0,0.0
971,99C,CITYWIDE SAVINGS INITIATIVES,2,Citywide Savings - OTPS,Y,-1.060000e+09,0.0,0.0,0.0,0.0,0.0,0.0,0.0
972,99D,PRIOR YEAR PAYABLES,2,OTHER THAN PERSONAL SERVICES,Y,0.000000e+00,0.0,0.0,0.0,-400000000.0,0.0,0.0,0.0
973,99P,ENERGY ADJUSTMENT,2,OTHER THAN PERSONAL SERVICES,Y,1.126900e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.0
974,99S,LEASE ADJUSTMENT,2,OTHER THAN PERSONAL SERVICES,Y,5.323043e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [43]:
UoA_collapsed_df.to_excel(f"current_api_{planned_fy}.xlsx",sheet_name="UoA",index=False)

## Agencies

In [44]:
UoA_collapsed_df.columns

Index(['agency_number', 'agency_name', 'unit_appropriation_number',
       'unit_appropriation_name', 'financial_plan_savings_flag',
       'FY27_financial_plan_amount_prelim',
       'FY27_financial_plan_position_prelim', 'FY26_current_adopted_amount',
       'FY26_current_modified_amount', 'FY27_financial_plan_amount_exec',
       'FY26_current_adopted_position', 'FY26_current_modified_position',
       'FY27_financial_plan_position_exec'],
      dtype='str')

In [45]:
Agency_collapsed_df = UoA_collapsed_df.groupby(['agency_number', 'agency_name']).sum().reset_index()

print(Agency_collapsed_df.columns[5:])

target_cols = Agency_collapsed_df.columns[5:]

Agency_collapsed_df = Agency_collapsed_df[['agency_number', 'agency_name', *target_cols]]

Agency_collapsed_df

Index(['FY27_financial_plan_amount_prelim',
       'FY27_financial_plan_position_prelim', 'FY26_current_adopted_amount',
       'FY26_current_modified_amount', 'FY27_financial_plan_amount_exec',
       'FY26_current_adopted_position', 'FY26_current_modified_position',
       'FY27_financial_plan_position_exec'],
      dtype='str')

,agency_number,agency_name,FY27_financial_plan_amount_prelim,FY27_financial_plan_position_prelim,FY26_current_adopted_amount,FY26_current_modified_amount,FY27_financial_plan_amount_exec,FY26_current_adopted_position,FY26_current_modified_position,FY27_financial_plan_position_exec
0,002,MAYORALTY,1.987918e+08,1402.0,206176143.0,207283515.0,209965286.0,1374.0,1397.0,1423.0
1,003,BOARD OF ELECTIONS,1.468751e+08,517.0,146875148.0,216647571.0,206972679.0,517.0,517.0,517.0
2,004,CAMPAIGN FINANCE BOARD,1.347705e+07,87.0,109481237.0,123881237.0,104093091.0,258.0,258.0,258.0
3,008,OFFICE OF THE ACTUARY,7.617044e+06,42.0,7614099.0,7677099.0,8483139.0,42.0,42.0,42.0
4,010,BOROUGH PRESIDENT - MANHATTAN,5.586632e+06,56.0,6017382.0,6194656.0,6079019.0,56.0,56.0,56.0
...,...,...,...,...,...,...,...,...,...,...
140,945,PUBLIC ADMINISTRATOR-RICHMOND COUNTY,6.555800e+05,5.0,673602.0,673602.0,657628.0,5.0,5.0,5.0
141,99C,CITYWIDE SAVINGS INITIATIVES,-1.060000e+09,0.0,0.0,0.0,0.0,0.0,0.0,0.0
142,99D,PRIOR YEAR PAYABLES,0.000000e+00,0.0,0.0,0.0,-400000000.0,0.0,0.0,0.0
143,99P,ENERGY ADJUSTMENT,1.126900e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.0
144,99S,LEASE ADJUSTMENT,5.323043e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [46]:
UoA_collapsed_df.to_excel(f"current_api_{planned_fy}.xlsx",sheet_name="UoA",index=False)